name: cooperativity
channels:
  - conda-forge
  - ambermd
  - defaults
dependencies:
  - python=3.8
  - codecov
  - matplotlib
  - seaborn
  - ambertools
  - pandas
  - scipy
  - biopython
  - jupyter
  - mdtraj
  - openpyxl
  - rdkit
